spring:
  application:
    name: lesson_service

  data:
    mongodb:
      uri: ${MONGO_URL}
server:
  port: 8082


eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/


